In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression


In [4]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [5]:
# Target (apples)
targets = np.array([[56], 
                    [81], 
                    [119], 
                    [22], 
                    [103]], dtype='float32')

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(inputs,targets,test_size=0.25, random_state=64)


In [15]:
regression = LinearRegression().fit(x_train,y_train)
print(regression)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [16]:
#To retrieve the intercept:
print(regression.intercept_)
#For retrieving the slope:
print(regression.coef_)


[20.937225]
[[-0.5451955  0.8507663  0.5429672]]


In [18]:
y_pred = regression.predict(x_test)
print(y_pred)
print(y_test)


[[80.941765]
 [61.486885]]
[[81.]
 [56.]]
