In [1]:
import numpy as np

In [11]:
#Create Two numpy array of size 3 X 2 and 2 X 3
array1 = np.array([[1, 2, 3],[4, 5, 6]])
array2 = np.array([[1,2],[3, 4],[5, 6]])
print(array1)
print(np.shape(array1))
print(array2)
print(np.shape(array2))

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [14]:
#Randomly Initalize that array
array1 = np.random.rand(2,3)
print(array1)
array2 = np.random.rand(3,2)
print(array2)

[[0.37570033 0.40746993 0.84787334]
 [0.05768381 0.7574894  0.07946646]]
[[0.78142704 0.30376413]
 [0.40522824 0.78763097]
 [0.7796498  0.20341481]]


In [15]:
# perform matrix multiplication
mul = np.dot(array1, array2)
print(mul)

[[1.119745   0.60753021]
 [0.4139878  0.63030904]]


In [16]:
# perform element wise matrix multiplication
res = [[0 for x in range(len(array1))] for y in range(len(array2[0]))]

for i in range(len(array1)): 
  for j in range(len(array2[0])): 
    for k in range(len(array2)): 
      res[i][j] += array1[i][k] * array2[k][j]
 
print (res)

[[1.1197449997419249, 0.6075302104607908], [0.4139877972354667, 0.6303090379761362]]


In [19]:
# mean of first matrix
mean = np.mean(array1)
print(mean)

0.42094721225425696


In [21]:
import pandas as pd
md = pd.read_csv("mtcars.csv")

In [22]:
# Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version
del md['model']
# meancenter
meancenter = md.apply(lambda e: e - e.mean())
print(meancenter.head())

        mpg     cyl        disp       hp      drat       wt     qsec      vs  \
0  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.59725 -1.38875 -0.4375   
1  0.909375 -0.1875  -70.721875 -36.6875  0.303437 -0.34225 -0.82875 -0.4375   
2  2.709375 -2.1875 -122.721875 -53.6875  0.253437 -0.89725  0.76125  0.5625   
3  1.309375 -0.1875   27.278125 -36.6875 -0.516563 -0.00225  1.59125  0.5625   
4 -1.390625  1.8125  129.278125  28.3125 -0.446563  0.22275 -0.82875 -0.4375   

        am    gear    carb  
0  0.59375  0.3125  1.1875  
1  0.59375  0.3125  1.1875  
2  0.59375  0.3125 -1.8125  
3 -0.40625 -0.6875 -1.8125  
4 -0.40625 -0.6875 -0.8125  
